language: generic # don't install any environment

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - lua5.1
      - liblua5.1-0-dev

before_install:
  - sudo apt-get install luarocks
  - sudo luarocks install penlight

script: lua run-rst-tests.lua && lua run-tests.lua
